# Generated by Django 4.2.2 on 2023-07-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_user_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
    ]
