# Generated by Django 4.2.2 on 2023-07-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_supervise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField(null=True)),
                ('password', models.CharField(max_length=100)),
                ('RePassword', models.CharField(max_length=100)),
            ],
        ),
    ]
