# Generated by Django 4.2.2 on 2023-07-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='password',
            new_name='Password',
        ),
    ]
