# Generated by Django 4.2.2 on 2023-07-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_rename_password_manager_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building_Name', models.TextField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
                ('Floor', models.CharField(max_length=100)),
                ('Identifer', models.TextField(max_length=100)),
                ('Structure', models.CharField(max_length=100)),
                ('Height', models.IntegerField(null=True)),
            ],
        ),
    ]
