# Generated by Django 4.2.2 on 2023-07-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='Building_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='Identifer',
            field=models.CharField(max_length=100),
        ),
    ]
