# Generated by Django 4.2.2 on 2023-07-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_building_building_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_Catagories', models.CharField(max_length=100)),
                ('Item_Name', models.CharField(max_length=100)),
                ('Total_Quantity', models.IntegerField(null=True)),
                ('Current_Date', models.DateField(null=True)),
            ],
        ),
    ]
