# Generated by Django 4.2.2 on 2023-07-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_To', models.TimeField(null=True)),
                ('Time_From', models.TimeField(null=True)),
                ('Permanent_Employee', models.IntegerField(null=True)),
                ('TemporaryEmployee', models.IntegerField(null=True)),
            ],
        ),
    ]
