# Generated by Django 4.2.2 on 2023-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='TemporaryEmployee',
        ),
        migrations.AddField(
            model_name='job',
            name='Temporary_Employee',
            field=models.IntegerField(null=True),
        ),
    ]
