# Generated by Django 4.2.2 on 2023-07-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_remove_job_temporaryemployee_job_temporary_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Temporary_Employee',
            new_name='Temporary_Employe',
        ),
    ]
