# Generated by Django 4.2.2 on 2023-07-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_rename_jobs_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiclee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_Catagories', models.CharField(max_length=100)),
                ('Vehicle_Number', models.CharField(max_length=20)),
                ('Description', models.IntegerField(max_length=200)),
            ],
        ),
    ]
