# Generated by Django 4.2.2 on 2023-07-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_vehiclee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclee',
            name='Description',
            field=models.IntegerField(max_length=100),
        ),
    ]
