# Generated by Django 4.2.2 on 2023-07-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_alter_vehiclee_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiclee',
            new_name='Www',
        ),
    ]
