# Generated by Django 4.2.2 on 2023-07-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_rename_vehiclee_www'),
    ]

    operations = [
        migrations.AlterField(
            model_name='www',
            name='Description',
            field=models.CharField(max_length=100),
        ),
    ]
