# Generated by Django 4.2.2 on 2023-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_alter_www_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='www',
            name='vehicle_Catagories',
            field=models.CharField(max_length=25),
        ),
    ]
