# Generated by Django 4.2.2 on 2023-07-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_alter_www_vehicle_catagories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagories', models.CharField(max_length=100)),
                ('Product_Name', models.CharField(max_length=50)),
                ('Total_Quantity', models.IntegerField(null=True)),
                ('Product_Details', models.CharField(max_length=100)),
            ],
        ),
    ]
