# Generated by Django 4.2.2 on 2023-07-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_remove_job_time_from_remove_job_time_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Time_In',
            field=models.TimeField(null=True),
        ),
    ]
