# Generated by Django 4.2.2 on 2023-07-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_user_time_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Time_In',
        ),
    ]
