# Generated by Django 4.2.2 on 2023-07-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.IntegerField(null=True)),
                ('Attendence', models.CharField(choices=[('P', 'present'), ('A', 'Absent')], max_length=25)),
            ],
        ),
    ]
