# Generated by Django 4.2.2 on 2023-07-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0027_attendenceform'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendenceform',
            name='Current_Date',
            field=models.DateField(null=True),
        ),
    ]
