# Generated by Django 4.2.2 on 2023-07-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_attendenceform_current_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('Box_id', models.AutoField(primary_key=True, serialize=False)),
                ('Box_Name', models.CharField(max_length=200)),
                ('Current_Date', models.DateField(null=True)),
            ],
        ),
    ]
