# Generated by Django 4.2.2 on 2023-07-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_box'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='Www',
            new_name='Veh',
        ),
    ]
