# Generated by Django 4.2.2 on 2023-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_rename_product_products_rename_www_veh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Total_Quantity',
            new_name='height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Item_Name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Stock_Catagories',
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='nof_bins',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rack_name',
            field=models.CharField(default='timezone.now', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
