# Generated by Django 4.2.2 on 2023-07-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0031_rename_total_quantity_item_height_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userr',
        ),
        migrations.RenameField(
            model_name='attendenceform',
            old_name='Employee_id',
            new_name='employee_id',
        ),
    ]
