# Generated by Django 4.2.2 on 2023-07-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0032_rename_user_userr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userr',
            new_name='User',
        ),
    ]
