# Generated by Django 4.2.2 on 2023-07-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0033_rename_userr_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
