# Generated by Django 4.2.2 on 2023-07-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0034_remove_user_id_alter_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foreign_key_fied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.building'),
        ),
    ]
