# Generated by Django 4.2.2 on 2023-07-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0035_item_foreign_key_fied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(max_length=30)),
                ('nof_bins', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('foreign_key_fied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.building')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
