# Generated by Django 4.2.2 on 2023-07-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0036_racks_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='foreign_key_fied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.racks'),
        ),
    ]
