# Generated by Django 4.2.2 on 2023-07-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0037_products_foreign_key_fied'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='building_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.building'),
        ),
        migrations.AddField(
            model_name='box',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.products'),
        ),
        migrations.AddField(
            model_name='box',
            name='rack_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.racks'),
        ),
    ]
