# Generated by Django 4.2.2 on 2023-07-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0039_signin_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='UserType',
            field=models.CharField(default='Manager', max_length=100),
        ),
    ]
