# Generated by Django 4.2.2 on 2023-07-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0042_alter_supervise_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervise',
            name='UserType',
            field=models.CharField(default='Supervisor', max_length=100),
        ),
    ]
