# Generated by Django 4.2.2 on 2023-07-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0043_alter_supervise_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='Email',
            new_name='email',
        ),
    ]
