# Generated by Django 4.2.2 on 2023-07-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0044_rename_email_manager_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserType',
            field=models.CharField(default='Employee', max_length=100),
        ),
    ]
