# Generated by Django 4.2.2 on 2023-07-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0045_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='email',
            new_name='Email',
        ),
    ]
