# Generated by Django 4.2.2 on 2023-07-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0047_rename_email_manager_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='Password',
            new_name='password',
        ),
    ]
