# Generated by Django 4.2.2 on 2023-08-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0049_alter_box_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='Total_No_Racks',
            field=models.IntegerField(null=True),
        ),
    ]
