# Generated by Django 4.2.2 on 2023-08-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0051_box_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='transit_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_action', models.CharField(max_length=50)),
                ('building', models.CharField(max_length=50)),
                ('rack', models.CharField(max_length=50)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.box')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.veh')),
            ],
        ),
    ]
