# Generated by Django 4.2.2 on 2023-09-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0053_box_action_box_vehicle_transit_delete_transit_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendenceform',
            name='Attendence',
        ),
        migrations.RemoveField(
            model_name='attendenceform',
            name='Current_Date',
        ),
        migrations.RemoveField(
            model_name='attendenceform',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='attendenceform',
            name='attendance_status',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendenceform',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.user'),
        ),
    ]
