# Generated by Django 4.2.2 on 2023-09-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0054_remove_attendenceform_attendence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendenceform',
            name='current_date',
            field=models.DateField(null=True),
        ),
    ]
