# Generated by Django 4.2.2 on 2023-09-14 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0058_signin_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='racks',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
